### ISSUE TITLE
Make https://github.com/Gamebuino/gamebuino-samd-peripherals.git public

### ISSUE THREAD

**Issue by BjoernSchilberg** [Gamebuino/Gamebuino-Circuitpython#1]
Hej, Aurélien,
I try to build the CircuitPython port of the gamebuino by myself. Unfortunately I already failed at the first step cloning the repo and the submodules, because it seems gamebuino-samd-peripherals is not a public repo. Could you please make the gamebuino-samd-peripherals open?

Thanks.

björn

**Comment by Sorunome** [comment]
@Rodot that is https://github.com/Rodot/gamebuino-samd-peripherals

**Comment by Rodot** [comment]
Done !
